# Generated by Django 2.0.4 on 2018-04-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_corporate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
