# Generated by Django 2.0.4 on 2018-04-09 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(default='media/avatar.jpg', upload_to='documents')),
                ('USD', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('EUR', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('RON', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('default_payment', models.IntegerField(blank=True, default=0)),
                ('corporate', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
