# Generated by Django 2.0.4 on 2018-04-09 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dot_basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=15)),
                ('csv', models.CharField(blank=True, max_length=3)),
                ('exp_date', models.CharField(blank=True, max_length=5, null=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=15)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('c_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
